---
title: "Project-QM"
author: "Karan, Rohit, Shubham"
date: "14/03/2022"
output: pdf_document
---
### Introduction 
Retailer's main goal is to provide right product at the right time to their customers.TO achieve this goal , retailer should be able to gauge the demand efficiently. Retail being the last downstream component of the supply chain, any fluctuations in the demand can disrupt the whole supply chain.
It is difficult to anticipate daily weather in advance but it has an immediate impact on daily business and sales.The use of weather forecasts to reduce demand uncertainty is restricted to retailers able to adjust their supply chain activities within two weeks.

1.1 Seasonality
Weather such as precipitation(snow and rain) can significantly influence shopper's decision. It is obscure how consumer will react to weather conditions, The shoppers may choose to consider good weather as a reason for engaging in outdoor activities and thus postpone or forgo purchases. On the other hand they might consider shopping in clear and sunny weather.
Holiday season can have pos
      
1.2. Psychological Effect
Weather can have significant    
People in good mood are more likely to spend more money and self reward themselves.Weather can have negative effect on an individual's mood. 
Bad weather can have a negative psychological impact on shopper's willingness to visit retail stores. It might cause them to shop online or postpone the plan of shopping.  #BrickandMortar. Psychological effects may lead to a change in shopping habits, e.g., bulk buying to hoard supplies. For example, lower prices during an extreme weather occurrence might trigger stock-ups (Gauri et al., 2017). Lower prices during extreme weather occurrences are common in retail settings (Beutel and Minner, 2012). It has been shown that the weather at the time of purchase heavily affects customers’ decisions for purchases, e.g., advance sales of outdoor events, when the weather at the time of purchase should be irrelevant. 

=======
1.Role of Weather 
  1.1. Seasonality  
  1.2. Psychological Effect

### Objective
In this study, we have evaluated the impact of weather on retail sales in the major provinces of Canada. We have used monthly agreegted data. We leveraged the data of 3 major retail players- Walmart, Costco and The Wholesale Food for analysing how the weather affects their retail sales.  
1.Role of Data
The objective of this research paper is to analyze the impact of weather on retail sales in 3 major Canadian cities- Montreal, Toronto and Vancouver. 
2. Footfall is our proxy variable.
We are assessing the retail sales through the footfall data of stores which acts as our proxy variable. (Graham, 2017; Makkar, 2020). 

3. Weather Variables -> snow, precipitation, sunlight
### Literature Review
Weather impact on retail sales has been studied for more than 50 years now (Steele, 1951), but still there are only a handful of studies that provide sophisticated econometric analysis of weather effect. Starr-McCluer (2000) examined the effects of temperature on total US retail sales. #

1. Past Articles -1.1 and 1.2
2. How our research is novel?
3. How footfall is related to Sales?
4. Hypotheses : 3/4 depending on independent variables.
5. Control Variables and there importances--- refer to articles
    a. CPI b. unemployability c. disposable income d. consumer confidence 
Talk about all sections of paper- what's done in which section.

### Data Collection and preprocessing 
safegraph
statista.ca 
Python/ R preprocessing

# Data Preperation
```{r, error=FALSE, include=FALSE}
#Import Libraries
library(tidyverse)
library(readxl)

df_cpi = read_excel("Data/controlVariables.xlsx", sheet= "CPI Index") #CPI Index
df_unemployability = read_excel("Data/controlVariables.xlsx", sheet= "UnemploymentRate") #Unemployability
df_income =  read_excel("Data/controlVariables.xlsx", sheet= "DisposableIncome")%>%
  select(Date, `British Columbia`, Ontario, Quebec) #Disposable Income
df_cc =  read_excel("Data/controlVariables.xlsx", sheet= "ConsumerConfidence") #Consumer Confidence

df_footfall = read.csv("Data/footfallFinal.csv") #Footfall data
df_weather = read.csv("Data/weatherDataFinal.csv")# Weather data

#Select only the required fields and change the formatting of the control variables to fit a panel data structure
df_weather <- df_weather %>% 
              select(date, max_temp, mean_temp, snow_grnd, 
                     spd_max_gust, total_rain,total_snow, total_precip, postal_code)

df_cpi <- df_cpi %>% pivot_longer(!Date, names_to = "region", values_to = "cpi")
df_unemployability <- df_unemployability %>% pivot_longer(!Date, names_to = "region", values_to = "unemployability")
df_income <- df_income %>% pivot_longer(!Date, names_to = "region", values_to = "disposableIncome")
df_cc <- df_cc %>% pivot_longer(!Date, names_to = "region", values_to = "ConsumerConfidence")

#Preparing data in the right format to combine them
df_cpi <- df_cpi %>% separate(Date, c("Year", "Month"))
df_unemployability <- df_unemployability %>% separate(Date, c("Year", "Month"))
df_income <- df_income %>% rename(Year = Date)
df_cc <- df_cc %>% separate(Date, c("Year", "Month"))

df_control <- merge(df_cc, df_cpi, by = c("region", "Year", "Month"))
df_control <- merge(df_control, df_income, by = c("region", "Year"))
df_control <- merge(df_control, df_unemployability, by = c("region", "Year", "Month"))

df_control <- df_control %>% mutate(region = case_when(region == "British Columbia" ~ "BC",
                                                       region == "Ontario" ~ "ON",
                                                       region == "Quebec" ~ "QC"))

df_footfall <- df_footfall %>% select(Date, visits_by_day, region, postal_code) %>% rename(date = Date)
data <- merge(df_footfall, df_weather, by = c("postal_code", "date"))
data <- data %>% separate(date, c("Year", "Month", "Day"))
data <- merge(data, df_control, by = c("region", "Year", "Month"), all.x = TRUE) #data is the final data for modelling
```

### EDA


### Modelling


### Results


### Conclusion